# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopManagment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShopManagment

  target 'ShopManagmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShopManagmentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
